/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Users数据访问接口
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Globalization;
using System.Text;

using Zkjj.Zgyinggu.BusinessEntities;

namespace Zkjj.Zgyinggu.DataAccess.Interface
{
	/// <summary>
	/// Users数据访问接口
	/// </summary>
	public partial interface IUsersDataAccess : IUsersDataAccessBase
	{
	}

	/// <summary>
	/// Users数据访问基础接口
	/// </summary>
	public interface IUsersDataAccessBase
	{

		/// <summary>
		/// 增加（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="users">Users</param>
		void Add(DbTransaction transaction, Users users);
		
		///// <summary>
		///// 增加
		///// </summary>
		///// <param name="users">Users</param>
		//public virtual void Add(Users users)
		//{
		//  Add(null, users);
		//}
		
		/// <summary>
		/// 删除（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="userId">UserId</param>
		void Remove(DbTransaction transaction, Int32 userId);
		
		///// <summary>
		///// 删除
		///// </summary>
		///// <param name="userId">UserId</param>
		//public virtual void Remove(Int32 userId)
		//{
		//  Remove(null, userId);
		//}
		
		/// <summary>
		/// 保存（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="users">Users</param>
		void Save(DbTransaction transaction, Users users);
		
		///// <summary>
		///// 保存
		///// </summary>
		///// <param name="users">Users</param>
		//public virtual void Save(Users users)
		//{
		//  Save(null, users);
		//}
		
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		/// <param name="userId">UserId</param>
		/// <returns>Users</returns>
		Users GetById(Int32 userId);

		/// <summary>
		/// 获取所有对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Users列表</returns>
		UsersList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression, out int totalRecords);
		
		
		/// <summary>
		/// 根据条件获取对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Users列表</returns>
		UsersList GetPagedListByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria, out int totalRecords);
	}
}
