/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	SubjectInfo业务逻辑
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Globalization;
using System.Runtime.Serialization;
using System.Text;

#if EnableWCF
using System.ServiceModel;
#endif
#if EnableDTC
using System.Transactions;
#endif

using Share.Framework;
using Share.Framework.Caching;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
using Zkjj.Zgyinggu.BusinessLogic.Caching;
using Zkjj.Zgyinggu.BusinessLogic.Logging;
using Zkjj.Zgyinggu.DataAccess;
using Zkjj.Zgyinggu.DataAccess;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#else
using Zkjj.Zgyinggu.DataAccess.SQLServer;
#endif
using Zkjj.Zgyinggu.Exceptions;
#if EnableWCF || EnableServiceContracts
using Zkjj.Zgyinggu.ServiceContracts;
#endif



namespace Zkjj.Zgyinggu.BusinessLogic
{
	/// <summary>
	/// SubjectInfo业务逻辑
	/// </summary>
	[System.ComponentModel.DataObject]
	public partial class SubjectInfoLogic : SubjectInfoLogicBase
#if EnableWCF || EnableServiceContracts
		, ISubjectInfoService
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// SubjectInfo业务逻辑基类
	/// </summary>
	public abstract class SubjectInfoLogicBase
	{
#if EnableIDAL
		protected static readonly ISubjectInfoDataAccess DalSubjectInfo = DalFactory.CreateSubjectInfo();//数据访问对象
#else
		protected static readonly SubjectInfoDataAccess DalSubjectInfo = new SubjectInfoDataAccess();//数据访问对象
#endif
		protected int _TotalRecords;//记录总数

		#region 缓存
		/// <summary>
		/// 移除根据标识获取SubjectInfo对象的缓存
		/// </summary>
		/// <param name="id">Id</param>
		protected internal virtual void RemoveGetByIdCache(Int32 id)
		{
			CacheHelper.Remove(BizCacheEnum.SubjectInfoGetById.ToString(), new string[] {id.ToString()}, true);
		}
		#endregion
		
		/// <summary>
		/// 增加
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="subjectInfo">SubjectInfo</param>
		internal virtual void Add(DbTransaction transaction, bool needLog, SubjectInfo subjectInfo)
		{
			DalSubjectInfo.Add(transaction, subjectInfo);
			
			if(needLog)
			{
				LogHelper.Instance().WriteBusinessLog(
					BizLogEnum.SubjectInfoAdd.ToString(),
					new StringBuilder().Append("Id: ").Append(subjectInfo.Id.ToString()).ToString(),
					"增加SubjectInfo");
			}
		}
		
		/// <summary>
		/// 增加
		/// </summary>
		/// <param name="subjectInfo">SubjectInfo</param>
		public virtual void Add(SubjectInfo subjectInfo)
		{
			Add(null, true, subjectInfo);
		}

		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="id">Id</param>
		internal virtual void Remove(DbTransaction transaction, bool needLog, Int32 id)
		{
			DalSubjectInfo.Remove(transaction, id);
			RemoveGetByIdCache(id);
			
			if(needLog)
			{
				LogHelper.Instance().WriteBusinessLog(
					BizLogEnum.SubjectInfoRemove.ToString(),
					new StringBuilder().Append("Id: ").Append(id.ToString()).ToString(),
					"删除SubjectInfo");
			}
		}
		
		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="id">Id</param>
		public virtual void Remove(Int32 id)
		{
			Remove(null, true, id);
		}

		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="subjectInfo">SubjectInfo</param>
		internal virtual void Remove(DbTransaction transaction, bool needLog, SubjectInfo subjectInfo)
		{
			Remove(transaction, needLog, subjectInfo.Id);
		}
		
		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="subjectInfo">SubjectInfo</param>
		public virtual void Remove(SubjectInfo subjectInfo)
		{
			Remove(null, true, subjectInfo);
		}
		    
		/// <summary>
		/// 保存
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="subjectInfo">SubjectInfo</param>
		internal virtual void Save(DbTransaction transaction, bool needLog, SubjectInfo subjectInfo)
		{
			DalSubjectInfo.Save(transaction, subjectInfo);
			RemoveGetByIdCache(subjectInfo.Id);
			
			if(needLog)
			{
				LogHelper.Instance().WriteBusinessLog(
					BizLogEnum.SubjectInfoSave.ToString(),
					new StringBuilder().Append("Id: ").Append(subjectInfo.Id.ToString()).ToString(),
					"保存SubjectInfo");
			}
		}

		/// <summary>
		/// 保存
		/// </summary>
		/// <param name="subjectInfo">SubjectInfo</param>
		public virtual void Save(SubjectInfo subjectInfo)
		{
			Save(null, true, subjectInfo);
		}
		
#if GetNewId
		/// <summary>
		/// 获取新ID（序列）
		/// </summary>
		/// <returns>新ID</returns>
		public virtual decimal GetNewId()
		{
			return DalSubjectInfo.GetNewId();
		}
#endif
    
		/// <summary>
		/// 根据标识获取SubjectInfo对象（如果没有满足条件的记录，抛出异常）
		/// </summary>
		/// <param name="id">Id</param>
		/// <returns>SubjectInfo</returns>
		public virtual SubjectInfo GetById(Int32 id)
		{
			return GetById(id, true);
		}	
		
		/// <summary>
		/// 根据标识获取SubjectInfo对象
		/// </summary>
		/// <param name="id">Id</param>
		/// <param name="throwNotFoundException">如果没有满足条件的记录是否抛出异常</param>
		/// <returns>SubjectInfo</returns>
		public virtual SubjectInfo GetById(Int32 id, bool throwNotFoundException)
		{
			SubjectInfo subjectInfo = CacheHelper.Get<SubjectInfo, Int32>(
				BizCacheEnum.SubjectInfoGetById.ToString(),
				id,
				new CacheMissedGetDataHandler<SubjectInfo, Int32>(DalSubjectInfo.GetById)
				);
			
			if (throwNotFoundException && subjectInfo == null)
			{
				SubjectInfoNotFoundException subjectInfoNotFoundException = new SubjectInfoNotFoundException(id);
#if EnableWCF
				throw new FaultException<SubjectInfoNotFoundException>(subjectInfoNotFoundException, subjectInfoNotFoundException.Message);
#else
				throw subjectInfoNotFoundException;
#endif
			}
			
			return subjectInfo;
		}		

		/// <summary>
		/// 获取所有SubjectInfo对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <returns>SubjectInfo列表</returns>
		public virtual SubjectInfoList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression)
		{
			SubjectInfoList subjectInfoList = DalSubjectInfo.GetPagedListAll(startRowIndex, maximumRows, sortExpression, out _TotalRecords);
			
			return subjectInfoList;
		}
		
		/// <summary>
		/// 获取所有SubjectInfo对象记录总数
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <returns>SubjectInfo记录总数</returns>
		public virtual int GetRowCountAll(int startRowIndex, int maximumRows, string sortExpression)
		{
			return _TotalRecords;
		}

#if GetPagedListByCriteria
		/// <summary>
		/// 根据条件获取SubjectInfo对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <returns>SubjectInfo列表</returns>
		internal virtual SubjectInfoList GetPagedListByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria)
		{
			SubjectInfoList subjectInfoList = DalSubjectInfo.GetPagedListByCriteria(startRowIndex, maximumRows, sortExpression, criteria, out _TotalRecords);
			
			return subjectInfoList;
		}
		
		/// <summary>
		/// 根据条件获取SubjectInfo对象记录总数
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <returns>SubjectInfo记录总数</returns>
		internal virtual int GetRowCountByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria)
		{
			return _TotalRecords;
		}
#endif
	}	
}

