/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Users业务逻辑
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/19 16:01:26
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Globalization;
using System.Runtime.Serialization;
using System.Text;

#if EnableWCF
using System.ServiceModel;
#endif
#if EnableDTC
using System.Transactions;
#endif

using Share.Framework;
using Share.Framework.Caching;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
using Zkjj.Zgyinggu.BusinessLogic.Caching;
using Zkjj.Zgyinggu.BusinessLogic.Logging;
using Zkjj.Zgyinggu.DataAccess;
using Zkjj.Zgyinggu.DataAccess;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#else
using Zkjj.Zgyinggu.DataAccess.SQLServer;
#endif
using Zkjj.Zgyinggu.Exceptions;
#if EnableWCF || EnableServiceContracts
using Zkjj.Zgyinggu.ServiceContracts;
#endif



namespace Zkjj.Zgyinggu.BusinessLogic
{
	/// <summary>
	/// Users业务逻辑
	/// </summary>
	[System.ComponentModel.DataObject]
	public partial class UsersLogic : UsersLogicBase
#if EnableWCF || EnableServiceContracts
		, IUsersService
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// Users业务逻辑基类
	/// </summary>
	public abstract class UsersLogicBase
	{
#if EnableIDAL
		protected static readonly IUsersDataAccess DalUsers = DalFactory.CreateUsers();//数据访问对象
#else
		protected static readonly UsersDataAccess DalUsers = new UsersDataAccess();//数据访问对象
#endif
		protected int _TotalRecords;//记录总数

		#region 缓存
		/// <summary>
		/// 移除根据标识获取Users对象的缓存
		/// </summary>
		/// <param name="userId">UserId</param>
		protected internal virtual void RemoveGetByIdCache(Int32 userId)
		{
			CacheHelper.Remove(BizCacheEnum.UsersGetById.ToString(), new string[] {userId.ToString()}, true);
		}
		#endregion
		
		/// <summary>
		/// 增加
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="users">Users</param>
		internal virtual void Add(DbTransaction transaction, bool needLog, Users users)
		{
			DalUsers.Add(transaction, users);
			
			if(needLog)
			{
				LogHelper.Instance().WriteBusinessLog(
					BizLogEnum.UsersAdd.ToString(),
					new StringBuilder().Append("UserId: ").Append(users.UserId.ToString()).ToString(),
					"增加Users");
			}
		}
		
		/// <summary>
		/// 增加
		/// </summary>
		/// <param name="users">Users</param>
		public virtual void Add(Users users)
		{
			Add(null, true, users);
		}

		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="userId">UserId</param>
		internal virtual void Remove(DbTransaction transaction, bool needLog, Int32 userId)
		{
			DalUsers.Remove(transaction, userId);
			RemoveGetByIdCache(userId);
			
			if(needLog)
			{
				LogHelper.Instance().WriteBusinessLog(
					BizLogEnum.UsersRemove.ToString(),
					new StringBuilder().Append("UserId: ").Append(userId.ToString()).ToString(),
					"删除Users");
			}
		}
		
		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="userId">UserId</param>
		public virtual void Remove(Int32 userId)
		{
			Remove(null, true, userId);
		}

		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="users">Users</param>
		internal virtual void Remove(DbTransaction transaction, bool needLog, Users users)
		{
			Remove(transaction, needLog, users.UserId);
		}
		
		/// <summary>
		/// 删除
		/// </summary>
		/// <param name="users">Users</param>
		public virtual void Remove(Users users)
		{
			Remove(null, true, users);
		}
		    
		/// <summary>
		/// 保存
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="needLog">是否记录日志</param>
		/// <param name="users">Users</param>
		internal virtual void Save(DbTransaction transaction, bool needLog, Users users)
		{
			DalUsers.Save(transaction, users);
			RemoveGetByIdCache(users.UserId);
			
			if(needLog)
			{
				LogHelper.Instance().WriteBusinessLog(
					BizLogEnum.UsersSave.ToString(),
					new StringBuilder().Append("UserId: ").Append(users.UserId.ToString()).ToString(),
					"保存Users");
			}
		}

		/// <summary>
		/// 保存
		/// </summary>
		/// <param name="users">Users</param>
		public virtual void Save(Users users)
		{
			Save(null, true, users);
		}
		
#if GetNewId
		/// <summary>
		/// 获取新ID（序列）
		/// </summary>
		/// <returns>新ID</returns>
		public virtual decimal GetNewId()
		{
			return DalUsers.GetNewId();
		}
#endif
    
		/// <summary>
		/// 根据标识获取Users对象（如果没有满足条件的记录，抛出异常）
		/// </summary>
		/// <param name="userId">UserId</param>
		/// <returns>Users</returns>
		public virtual Users GetById(Int32 userId)
		{
			return GetById(userId, true);
		}	
		
		/// <summary>
		/// 根据标识获取Users对象
		/// </summary>
		/// <param name="userId">UserId</param>
		/// <param name="throwNotFoundException">如果没有满足条件的记录是否抛出异常</param>
		/// <returns>Users</returns>
		public virtual Users GetById(Int32 userId, bool throwNotFoundException)
		{
			Users users = CacheHelper.Get<Users, Int32>(
				BizCacheEnum.UsersGetById.ToString(),
				userId,
				new CacheMissedGetDataHandler<Users, Int32>(DalUsers.GetById)
				);
			
			if (throwNotFoundException && users == null)
			{
				UsersNotFoundException usersNotFoundException = new UsersNotFoundException(userId);
#if EnableWCF
				throw new FaultException<UsersNotFoundException>(usersNotFoundException, usersNotFoundException.Message);
#else
				throw usersNotFoundException;
#endif
			}
			
			return users;
		}		

		/// <summary>
		/// 获取所有Users对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <returns>Users列表</returns>
		public virtual UsersList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression)
		{
			UsersList usersList = DalUsers.GetPagedListAll(startRowIndex, maximumRows, sortExpression, out _TotalRecords);
			
			return usersList;
		}
		
		/// <summary>
		/// 获取所有Users对象记录总数
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <returns>Users记录总数</returns>
		public virtual int GetRowCountAll(int startRowIndex, int maximumRows, string sortExpression)
		{
			return _TotalRecords;
		}

#if GetPagedListByCriteria
		/// <summary>
		/// 根据条件获取Users对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <returns>Users列表</returns>
		internal virtual UsersList GetPagedListByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria)
		{
			UsersList usersList = DalUsers.GetPagedListByCriteria(startRowIndex, maximumRows, sortExpression, criteria, out _TotalRecords);
			
			return usersList;
		}
		
		/// <summary>
		/// 根据条件获取Users对象记录总数
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <returns>Users记录总数</returns>
		internal virtual int GetRowCountByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria)
		{
			return _TotalRecords;
		}
#endif
	}	
}

