/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Subject数据访问
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Globalization;
using System.Text;

using Microsoft.ApplicationBlocks.Data;

using Share.Framework.Data;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#endif

namespace Zkjj.Zgyinggu.DataAccess.SQLServer
{
	/// <summary>
	/// Subject数据访问
	/// </summary>
	public partial class SubjectDataAccess : SubjectDataAccessBase
#if EnableIDAL
		, ISubjectDataAccess
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// Subject数据访问基类
	/// </summary>
	public class SubjectDataAccessBase
	{

		/// <summary>
		/// 增加（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="subject">Subject</param>
		public virtual void Add(DbTransaction transaction, Subject subject)
		{
			string commandName = "dbo.Pr_Subject_Insert";
						
			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@CategoryId", SqlDbType.Int),
					new SqlParameter("@SubjectName", SqlDbType.NVarChar, 200),
					new SqlParameter("@CreatorId", SqlDbType.Int),
					new SqlParameter("@CreatorName", SqlDbType.NChar, 10),
					new SqlParameter("@CreateTime", SqlDbType.DateTime),
					new SqlParameter("@DisplayOrder", SqlDbType.Int)
					};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}

			#region 输出参数设置
			parms[0].Direction = ParameterDirection.Output;
			#endregion
			
			#region 参数赋值
			if (subject.CategoryId != null){ parms[1].Value = subject.CategoryId; } else { parms[1].Value = DBNull.Value; }
			parms[2].Value = subject.SubjectName;
			parms[3].Value = subject.CreatorId;
			parms[4].Value = subject.CreatorName;
			parms[5].Value = subject.CreateTime;
			parms[6].Value = subject.DisplayOrder;
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("SubjectId: ").Append(parms[0].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[1].Direction.ToString()).Append(")").Append("CategoryId: ").Append(parms[1].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[2].Direction.ToString()).Append(")").Append("SubjectName: ").Append(parms[2].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[3].Direction.ToString()).Append(")").Append("CreatorId: ").Append(parms[3].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[4].Direction.ToString()).Append(")").Append("CreatorName: ").Append(parms[4].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[5].Direction.ToString()).Append(")").Append("CreateTime: ").Append(parms[5].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[6].Direction.ToString()).Append(")").Append("DisplayOrder: ").Append(parms[6].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Insert, null);
				throw;
			}

			#region 获取输出参数值
			subject.SubjectId = (Int32)parms[0].Value;
			#endregion
		}

		///// <summary>
		///// 增加
		///// </summary>
		///// <param name="subject">Subject</param>
		//public virtual void Add(Subject subject)
		//{
		//  Add(null, subject);
		//}
		
		/// <summary>
		/// 删除（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="subjectId">SubjectId</param>
		public virtual void Remove(DbTransaction transaction, Int32 subjectId)
		{
			string commandName = "dbo.Pr_Subject_Delete";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@SubjectId", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = subjectId;
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("SubjectId: ").Append(parms[0].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Delete, new string[] { subjectId.ToString() });
				throw;
			}
		}

		///// <summary>
		///// 删除
		///// </summary>
		///// <param name="subjectId">SubjectId</param>
		//public virtual void Remove(Int32 subjectId)
		//{
		//  Remove(null, subjectId);
		//}
		
		/// <summary>
		/// 保存（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="subject">Subject</param>
		public virtual void Save(DbTransaction transaction, Subject subject)
		{
			string commandName = "dbo.Pr_Subject_Update";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@CategoryId", SqlDbType.Int),
					new SqlParameter("@SubjectName", SqlDbType.NVarChar, 200),
					new SqlParameter("@CreatorId", SqlDbType.Int),
					new SqlParameter("@CreatorName", SqlDbType.NChar, 10),
					new SqlParameter("@CreateTime", SqlDbType.DateTime),
					new SqlParameter("@DisplayOrder", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = subject.SubjectId;
			if (subject.CategoryId != null){ parms[1].Value = subject.CategoryId; } else { parms[1].Value = DBNull.Value; }
			parms[2].Value = subject.SubjectName;
			parms[3].Value = subject.CreatorId;
			parms[4].Value = subject.CreatorName;
			parms[5].Value = subject.CreateTime;
			parms[6].Value = subject.DisplayOrder;
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("SubjectId: ").Append(parms[0].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[1].Direction.ToString()).Append(")").Append("CategoryId: ").Append(parms[1].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[2].Direction.ToString()).Append(")").Append("SubjectName: ").Append(parms[2].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[3].Direction.ToString()).Append(")").Append("CreatorId: ").Append(parms[3].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[4].Direction.ToString()).Append(")").Append("CreatorName: ").Append(parms[4].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[5].Direction.ToString()).Append(")").Append("CreateTime: ").Append(parms[5].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[6].Direction.ToString()).Append(")").Append("DisplayOrder: ").Append(parms[6].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Update, null);
				throw;
			}
		}

		///// <summary>
		///// 保存
		///// </summary>
		///// <param name="subject">Subject</param>
		//public virtual void Save(Subject subject)
		//{
		//  Save(null, subject);
		//}
		
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		/// <param name="subjectId">SubjectId</param>
		/// <returns>Subject</returns>
		public virtual Subject GetById(Int32 subjectId)
		{
			Subject subject = null;
			
			string commandName = "dbo.Pr_Subject_GetByPk";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@SubjectId", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = subjectId;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.StoredProcedure, commandName, parms))
			{
				if (dataReader.Read())
				{
					subject = PopulateSubjectFromDataReader(dataReader);
				}
			}
			
			return subject;
		}
	
		/// <summary>
		/// 获取所有对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Subject列表</returns>
		public virtual SubjectList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression, out int totalRecords)
		{
			SubjectList subjectList = new SubjectList();
			
			string commandName = "dbo.Pr_Subject_GetPagedListAll";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@StartRowIndex", SqlDbType.Int),
					new SqlParameter("@MaximumRows", SqlDbType.Int),
					new SqlParameter("@SortExpression", SqlDbType.VarChar),
					new SqlParameter("@ReturnValue", SqlDbType.Int, 4, ParameterDirection.ReturnValue, false, 0, 0, String.Empty, DataRowVersion.Default, null)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = startRowIndex;
			parms[1].Value = maximumRows;
			parms[2].Value = sortExpression;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.StoredProcedure, commandName, parms))
			{
				while (dataReader.Read())
				{
					subjectList.Add(PopulateSubjectFromDataReader(dataReader));
				}
			}
			
			#region 获取输出参数值
			totalRecords = (int)parms[3].Value;
			#endregion
			
			return subjectList;
		}
		
		/// <summary>
		/// 从DataReader中读取数据到业务对象
		/// </summary>
		/// <param name="reader">DataReader</param>
		/// <returns>Subject</returns>
		protected virtual Subject PopulateSubjectFromDataReader(SqlDataReader reader)
		{
			return DataReaderUtility.FillData<Subject>(reader);
		}
	}
}
