/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	SubjectInfo数据访问
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Globalization;
using System.Text;

using Microsoft.ApplicationBlocks.Data;

using Share.Framework.Data;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#endif

namespace Zkjj.Zgyinggu.DataAccess.SQLServer
{
	/// <summary>
	/// SubjectInfo数据访问
	/// </summary>
	public partial class SubjectInfoDataAccess : SubjectInfoDataAccessBase
#if EnableIDAL
		, ISubjectInfoDataAccess
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// SubjectInfo数据访问基类
	/// </summary>
	public class SubjectInfoDataAccessBase
	{

		/// <summary>
		/// 增加（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="subjectInfo">SubjectInfo</param>
		public virtual void Add(DbTransaction transaction, SubjectInfo subjectInfo)
		{
			string commandName = "dbo.Pr_SubjectInfo_Insert";
						
			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int),
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@FileName", SqlDbType.NVarChar, 50),
					new SqlParameter("@FileUrl", SqlDbType.NVarChar, 200)
					};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}

			#region 输出参数设置
			parms[0].Direction = ParameterDirection.Output;
			#endregion
			
			#region 参数赋值
			if (subjectInfo.SubjectId != null){ parms[1].Value = subjectInfo.SubjectId; } else { parms[1].Value = DBNull.Value; }
			if (subjectInfo.FileName != null){ parms[2].Value = subjectInfo.FileName; } else { parms[2].Value = DBNull.Value; }
			if (subjectInfo.FileUrl != null){ parms[3].Value = subjectInfo.FileUrl; } else { parms[3].Value = DBNull.Value; }
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("Id: ").Append(parms[0].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[1].Direction.ToString()).Append(")").Append("SubjectId: ").Append(parms[1].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[2].Direction.ToString()).Append(")").Append("FileName: ").Append(parms[2].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[3].Direction.ToString()).Append(")").Append("FileUrl: ").Append(parms[3].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Insert, null);
				throw;
			}

			#region 获取输出参数值
			subjectInfo.Id = (Int32)parms[0].Value;
			#endregion
		}

		///// <summary>
		///// 增加
		///// </summary>
		///// <param name="subjectInfo">SubjectInfo</param>
		//public virtual void Add(SubjectInfo subjectInfo)
		//{
		//  Add(null, subjectInfo);
		//}
		
		/// <summary>
		/// 删除（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="id">Id</param>
		public virtual void Remove(DbTransaction transaction, Int32 id)
		{
			string commandName = "dbo.Pr_SubjectInfo_Delete";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = id;
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("Id: ").Append(parms[0].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Delete, new string[] { id.ToString() });
				throw;
			}
		}

		///// <summary>
		///// 删除
		///// </summary>
		///// <param name="id">Id</param>
		//public virtual void Remove(Int32 id)
		//{
		//  Remove(null, id);
		//}
		
		/// <summary>
		/// 保存（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="subjectInfo">SubjectInfo</param>
		public virtual void Save(DbTransaction transaction, SubjectInfo subjectInfo)
		{
			string commandName = "dbo.Pr_SubjectInfo_Update";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int),
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@FileName", SqlDbType.NVarChar, 50),
					new SqlParameter("@FileUrl", SqlDbType.NVarChar, 200)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = subjectInfo.Id;
			if (subjectInfo.SubjectId != null){ parms[1].Value = subjectInfo.SubjectId; } else { parms[1].Value = DBNull.Value; }
			if (subjectInfo.FileName != null){ parms[2].Value = subjectInfo.FileName; } else { parms[2].Value = DBNull.Value; }
			if (subjectInfo.FileUrl != null){ parms[3].Value = subjectInfo.FileUrl; } else { parms[3].Value = DBNull.Value; }
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("Id: ").Append(parms[0].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[1].Direction.ToString()).Append(")").Append("SubjectId: ").Append(parms[1].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[2].Direction.ToString()).Append(")").Append("FileName: ").Append(parms[2].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[3].Direction.ToString()).Append(")").Append("FileUrl: ").Append(parms[3].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Update, null);
				throw;
			}
		}

		///// <summary>
		///// 保存
		///// </summary>
		///// <param name="subjectInfo">SubjectInfo</param>
		//public virtual void Save(SubjectInfo subjectInfo)
		//{
		//  Save(null, subjectInfo);
		//}
		
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		/// <param name="id">Id</param>
		/// <returns>SubjectInfo</returns>
		public virtual SubjectInfo GetById(Int32 id)
		{
			SubjectInfo subjectInfo = null;
			
			string commandName = "dbo.Pr_SubjectInfo_GetByPk";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = id;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.StoredProcedure, commandName, parms))
			{
				if (dataReader.Read())
				{
					subjectInfo = PopulateSubjectInfoFromDataReader(dataReader);
				}
			}
			
			return subjectInfo;
		}
	
		/// <summary>
		/// 获取所有对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>SubjectInfo列表</returns>
		public virtual SubjectInfoList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression, out int totalRecords)
		{
			SubjectInfoList subjectInfoList = new SubjectInfoList();
			
			string commandName = "dbo.Pr_SubjectInfo_GetPagedListAll";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@StartRowIndex", SqlDbType.Int),
					new SqlParameter("@MaximumRows", SqlDbType.Int),
					new SqlParameter("@SortExpression", SqlDbType.VarChar),
					new SqlParameter("@ReturnValue", SqlDbType.Int, 4, ParameterDirection.ReturnValue, false, 0, 0, String.Empty, DataRowVersion.Default, null)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = startRowIndex;
			parms[1].Value = maximumRows;
			parms[2].Value = sortExpression;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.StoredProcedure, commandName, parms))
			{
				while (dataReader.Read())
				{
					subjectInfoList.Add(PopulateSubjectInfoFromDataReader(dataReader));
				}
			}
			
			#region 获取输出参数值
			totalRecords = (int)parms[3].Value;
			#endregion
			
			return subjectInfoList;
		}
		
		/// <summary>
		/// 从DataReader中读取数据到业务对象
		/// </summary>
		/// <param name="reader">DataReader</param>
		/// <returns>SubjectInfo</returns>
		protected virtual SubjectInfo PopulateSubjectInfoFromDataReader(SqlDataReader reader)
		{
			return DataReaderUtility.FillData<SubjectInfo>(reader);
		}
	}
}
