/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Users数据访问
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/19 16:01:26
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Globalization;
using System.Text;

using Microsoft.ApplicationBlocks.Data;

using Share.Framework.Data;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#endif

namespace Zkjj.Zgyinggu.DataAccess.SQLServer
{
	/// <summary>
	/// Users数据访问
	/// </summary>
	public partial class UsersDataAccess : UsersDataAccessBase
#if EnableIDAL
		, IUsersDataAccess
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// Users数据访问基类
	/// </summary>
	public class UsersDataAccessBase
	{

		/// <summary>
		/// 增加（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="users">Users</param>
		public virtual void Add(DbTransaction transaction, Users users)
		{
			string commandName = "dbo.Pr_Users_Insert";
						
			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int),
					new SqlParameter("@UserName", SqlDbType.NVarChar, 50),
					new SqlParameter("@Password", SqlDbType.NVarChar, 100),
					new SqlParameter("@DisplayName", SqlDbType.NVarChar, 50),
					new SqlParameter("@UserHeadImg", SqlDbType.NVarChar, 200),
					new SqlParameter("@Email", SqlDbType.NVarChar, 200)
					};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}

			#region 输出参数设置
			parms[0].Direction = ParameterDirection.Output;
			#endregion
			
			#region 参数赋值
			parms[1].Value = users.UserName;
			parms[2].Value = users.Password;
			parms[3].Value = users.DisplayName;
			parms[4].Value = users.UserHeadImg;
			if (users.Email != null){ parms[5].Value = users.Email; } else { parms[5].Value = DBNull.Value; }
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("UserId: ").Append(parms[0].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[1].Direction.ToString()).Append(")").Append("UserName: ").Append(parms[1].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[2].Direction.ToString()).Append(")").Append("Password: ").Append(parms[2].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[3].Direction.ToString()).Append(")").Append("DisplayName: ").Append(parms[3].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[4].Direction.ToString()).Append(")").Append("UserHeadImg: ").Append(parms[4].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[5].Direction.ToString()).Append(")").Append("Email: ").Append(parms[5].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Insert, null);
				throw;
			}

			#region 获取输出参数值
			users.UserId = (Int32)parms[0].Value;
			#endregion
		}

		///// <summary>
		///// 增加
		///// </summary>
		///// <param name="users">Users</param>
		//public virtual void Add(Users users)
		//{
		//  Add(null, users);
		//}
		
		/// <summary>
		/// 删除（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="userId">UserId</param>
		public virtual void Remove(DbTransaction transaction, Int32 userId)
		{
			string commandName = "dbo.Pr_Users_Delete";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = userId;
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("UserId: ").Append(parms[0].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Delete, new string[] { userId.ToString() });
				throw;
			}
		}

		///// <summary>
		///// 删除
		///// </summary>
		///// <param name="userId">UserId</param>
		//public virtual void Remove(Int32 userId)
		//{
		//  Remove(null, userId);
		//}
		
		/// <summary>
		/// 保存（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="users">Users</param>
		public virtual void Save(DbTransaction transaction, Users users)
		{
			string commandName = "dbo.Pr_Users_Update";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int),
					new SqlParameter("@UserName", SqlDbType.NVarChar, 50),
					new SqlParameter("@Password", SqlDbType.NVarChar, 100),
					new SqlParameter("@DisplayName", SqlDbType.NVarChar, 50),
					new SqlParameter("@UserHeadImg", SqlDbType.NVarChar, 200),
					new SqlParameter("@Email", SqlDbType.NVarChar, 200)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = users.UserId;
			parms[1].Value = users.UserName;
			parms[2].Value = users.Password;
			parms[3].Value = users.DisplayName;
			parms[4].Value = users.UserHeadImg;
			if (users.Email != null){ parms[5].Value = users.Email; } else { parms[5].Value = DBNull.Value; }
			#endregion
			#endregion
			
			#region 数据调试日志
			StringBuilder dataDebugInfo = new StringBuilder(string.Format("准备执行{0}, 参数如下：", commandName));
			dataDebugInfo.AppendLine().Append("(").Append(parms[0].Direction.ToString()).Append(")").Append("UserId: ").Append(parms[0].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[1].Direction.ToString()).Append(")").Append("UserName: ").Append(parms[1].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[2].Direction.ToString()).Append(")").Append("Password: ").Append(parms[2].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[3].Direction.ToString()).Append(")").Append("DisplayName: ").Append(parms[3].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[4].Direction.ToString()).Append(")").Append("UserHeadImg: ").Append(parms[4].Value);
			dataDebugInfo.AppendLine().Append("(").Append(parms[5].Direction.ToString()).Append(")").Append("Email: ").Append(parms[5].Value);
			LogHelper.Instance().WriteBusinessLog("DataDebug", dataDebugInfo.ToString(), "数据调试");
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Update, null);
				throw;
			}
		}

		///// <summary>
		///// 保存
		///// </summary>
		///// <param name="users">Users</param>
		//public virtual void Save(Users users)
		//{
		//  Save(null, users);
		//}
		
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		/// <param name="userId">UserId</param>
		/// <returns>Users</returns>
		public virtual Users GetById(Int32 userId)
		{
			Users users = null;
			
			string commandName = "dbo.Pr_Users_GetByPk";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = userId;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.StoredProcedure, commandName, parms))
			{
				if (dataReader.Read())
				{
					users = PopulateUsersFromDataReader(dataReader);
				}
			}
			
			return users;
		}
	
		/// <summary>
		/// 获取所有对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Users列表</returns>
		public virtual UsersList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression, out int totalRecords)
		{
			UsersList usersList = new UsersList();
			
			string commandName = "dbo.Pr_Users_GetPagedListAll";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@StartRowIndex", SqlDbType.Int),
					new SqlParameter("@MaximumRows", SqlDbType.Int),
					new SqlParameter("@SortExpression", SqlDbType.VarChar),
					new SqlParameter("@ReturnValue", SqlDbType.Int, 4, ParameterDirection.ReturnValue, false, 0, 0, String.Empty, DataRowVersion.Default, null)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = startRowIndex;
			parms[1].Value = maximumRows;
			parms[2].Value = sortExpression;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.StoredProcedure, commandName, parms))
			{
				while (dataReader.Read())
				{
					usersList.Add(PopulateUsersFromDataReader(dataReader));
				}
			}
			
			#region 获取输出参数值
			totalRecords = (int)parms[3].Value;
			#endregion
			
			return usersList;
		}
		
		/// <summary>
		/// 从DataReader中读取数据到业务对象
		/// </summary>
		/// <param name="reader">DataReader</param>
		/// <returns>Users</returns>
		protected virtual Users PopulateUsersFromDataReader(SqlDataReader reader)
		{
			return DataReaderUtility.FillData<Users>(reader);
		}
	}
}
