/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Subject未找到异常
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Text;

using System.Globalization;
using System.Runtime.Serialization;

namespace Zkjj.Zgyinggu.Exceptions
{

	#region Subject未找到异常
	/// <summary>
	/// Subject未找到异常
	/// </summary>
#if EnableWCF
	[DataContract]
#else
	[Serializable]
#endif
	public class SubjectNotFoundException
#if EnableWCF
	
#else
	: Exception
#endif
	{
		private string _message;
		
		public SubjectNotFoundException()
		{		
		}
		
		/// <summary>
		/// 未找到此数据项的异常
		/// </summary>
		/// <param name="subjectId">SubjectId</param>

		/// <remarks>错误信息见ExceptionMessage.cs文件</remarks>
		public SubjectNotFoundException(Int32 subjectId)
#if EnableWCF
		{
			this._message = string.Format(ExceptionMessage.SubjectNotFoundMessage, subjectId);
		}
#else
			: this(string.Format(ExceptionMessage.SubjectNotFoundMessage, subjectId), null as Exception)
		{		
		}
#endif

#if EnableWCF
		/// <summary>
		/// 异常消息
		/// </summary>
		[DataMember]
		public string Message
		{
			get { return this._message; }
			set { this._message = value; }
		}
#else
		public SubjectNotFoundException(string message, Exception inner)
			: base(message, inner)
		{
		}
		
		protected SubjectNotFoundException(SerializationInfo info, StreamingContext context)
			: base(info, context)
		{
		}
#endif
	}
	#endregion

}
