/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Comment业务实体
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Text;

#if EnableWCF
using System.Runtime.Serialization;
#endif

namespace Zkjj.Zgyinggu.BusinessEntities
{
	/// <summary>
	/// Comment业务实体
	/// </summary>
#if EnableWCF
	[DataContract] [Serializable]
#else
	[Serializable]
#endif
	public partial class Comment : CommentBase
	{
		#region Constructor
		/// <summary>
		/// Comment构造函数--默认
		/// </summary>
		public Comment()
			: base()
		{
		}
		
		/// <summary>
		/// Comment构造函数--所有属性
		/// </summary>
		/// <param name="id">Id</param>
		/// <param name="commentContent">回复内容</param>
		/// <param name="subjectId">SubjectId</param>
		/// <param name="creatorId">CreatorId</param>
		/// <param name="creatorName">CreatorName</param>
		/// <param name="createTime">CreateTime</param>
		public Comment(Int32 id, String commentContent, Int32 subjectId, Int32 creatorId, String creatorName, DateTime createTime)
			: base(id, commentContent, subjectId, creatorId, creatorName, createTime)
		{
		}
		
		#endregion Constructor
	}
	
	/// <summary>
	/// Comment业务实体基类
	/// </summary>
#if EnableWCF
	[DataContract] [Serializable]
#else
	[Serializable]
#endif
	public abstract partial class CommentBase
	{
		#region Constructor
		/// <summary>
		/// Comment构造函数--默认
		/// </summary>
		protected CommentBase()
		{
		}
		
		/// <summary>
		/// Comment构造函数--所有属性
		/// </summary>
		/// <param name="id">Id</param>
		/// <param name="commentContent">回复内容</param>
		/// <param name="subjectId">SubjectId</param>
		/// <param name="creatorId">CreatorId</param>
		/// <param name="creatorName">CreatorName</param>
		/// <param name="createTime">CreateTime</param>
		protected CommentBase(Int32 id, String commentContent, Int32 subjectId, Int32 creatorId, String creatorName, DateTime createTime)
		{
			this.idField = id;
			this.commentContentField = commentContent;
			this.subjectIdField = subjectId;
			this.creatorIdField = creatorId;
			this.creatorNameField = creatorName;
			this.createTimeField = createTime;
		}
		
		#endregion Constructor
		
		#region Fields, Properties
		private Int32 idField;
		/// <summary>
		/// Id
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32 Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
		
		private String commentContentField;
		/// <summary>
		/// 回复内容
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual String CommentContent
		{
			get
			{
				return this.commentContentField;
			}
			set
			{
				this.commentContentField = value;
			}
		}
		
		private Int32 subjectIdField;
		/// <summary>
		/// SubjectId
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32 SubjectId
		{
			get
			{
				return this.subjectIdField;
			}
			set
			{
				this.subjectIdField = value;
			}
		}
		
		private Int32 creatorIdField;
		/// <summary>
		/// CreatorId
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32 CreatorId
		{
			get
			{
				return this.creatorIdField;
			}
			set
			{
				this.creatorIdField = value;
			}
		}
		
		private String creatorNameField;
		/// <summary>
		/// CreatorName
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual String CreatorName
		{
			get
			{
				return this.creatorNameField;
			}
			set
			{
				this.creatorNameField = value;
			}
		}
		
		private DateTime createTimeField;
		/// <summary>
		/// CreateTime
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual DateTime CreateTime
		{
			get
			{
				return this.createTimeField;
			}
			set
			{
				this.createTimeField = value;
			}
		}
		
		#endregion Fields, Properties
	}
}
