/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Subject业务实体
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Text;

#if EnableWCF
using System.Runtime.Serialization;
#endif

namespace Zkjj.Zgyinggu.BusinessEntities
{
	/// <summary>
	/// Subject业务实体
	/// </summary>
#if EnableWCF
	[DataContract] [Serializable]
#else
	[Serializable]
#endif
	public partial class Subject : SubjectBase
	{
		#region Constructor
		/// <summary>
		/// Subject构造函数--默认
		/// </summary>
		public Subject()
			: base()
		{
		}
		
		/// <summary>
		/// Subject构造函数--所有属性
		/// </summary>
		/// <param name="subjectId">SubjectId</param>
		/// <param name="categoryId">论坛类别</param>
		/// <param name="subjectName">SubjectName</param>
		/// <param name="creatorId">CreatorId</param>
		/// <param name="creatorName">CreatorName</param>
		/// <param name="createTime">CreateTime</param>
		/// <param name="displayOrder">显示顺序</param>
		public Subject(Int32 subjectId, Int32? categoryId, String subjectName, Int32 creatorId, String creatorName, DateTime createTime, Int32 displayOrder)
			: base(subjectId, categoryId, subjectName, creatorId, creatorName, createTime, displayOrder)
		{
		}
		
		#endregion Constructor
	}
	
	/// <summary>
	/// Subject业务实体基类
	/// </summary>
#if EnableWCF
	[DataContract] [Serializable]
#else
	[Serializable]
#endif
	public abstract partial class SubjectBase
	{
		#region Constructor
		/// <summary>
		/// Subject构造函数--默认
		/// </summary>
		protected SubjectBase()
		{
		}
		
		/// <summary>
		/// Subject构造函数--所有属性
		/// </summary>
		/// <param name="subjectId">SubjectId</param>
		/// <param name="categoryId">论坛类别</param>
		/// <param name="subjectName">SubjectName</param>
		/// <param name="creatorId">CreatorId</param>
		/// <param name="creatorName">CreatorName</param>
		/// <param name="createTime">CreateTime</param>
		/// <param name="displayOrder">显示顺序</param>
		protected SubjectBase(Int32 subjectId, Int32? categoryId, String subjectName, Int32 creatorId, String creatorName, DateTime createTime, Int32 displayOrder)
		{
			this.subjectIdField = subjectId;
			this.categoryIdField = categoryId;
			this.subjectNameField = subjectName;
			this.creatorIdField = creatorId;
			this.creatorNameField = creatorName;
			this.createTimeField = createTime;
			this.displayOrderField = displayOrder;
		}
		
		#endregion Constructor
		
		#region Fields, Properties
		private Int32 subjectIdField;
		/// <summary>
		/// SubjectId
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32 SubjectId
		{
			get
			{
				return this.subjectIdField;
			}
			set
			{
				this.subjectIdField = value;
			}
		}
		
		private Int32? categoryIdField;
		/// <summary>
		/// 论坛类别
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32? CategoryId
		{
			get
			{
				return this.categoryIdField;
			}
			set
			{
				this.categoryIdField = value;
			}
		}
		
		private String subjectNameField;
		/// <summary>
		/// SubjectName
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual String SubjectName
		{
			get
			{
				return this.subjectNameField;
			}
			set
			{
				this.subjectNameField = value;
			}
		}
		
		private Int32 creatorIdField;
		/// <summary>
		/// CreatorId
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32 CreatorId
		{
			get
			{
				return this.creatorIdField;
			}
			set
			{
				this.creatorIdField = value;
			}
		}
		
		private String creatorNameField;
		/// <summary>
		/// CreatorName
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual String CreatorName
		{
			get
			{
				return this.creatorNameField;
			}
			set
			{
				this.creatorNameField = value;
			}
		}
		
		private DateTime createTimeField;
		/// <summary>
		/// CreateTime
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual DateTime CreateTime
		{
			get
			{
				return this.createTimeField;
			}
			set
			{
				this.createTimeField = value;
			}
		}
		
		private Int32 displayOrderField;
		/// <summary>
		/// 显示顺序
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32 DisplayOrder
		{
			get
			{
				return this.displayOrderField;
			}
			set
			{
				this.displayOrderField = value;
			}
		}
		
		#endregion Fields, Properties
	}
}
