/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	SubjectCategory业务实体
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Text;

#if EnableWCF
using System.Runtime.Serialization;
#endif

namespace Zkjj.Zgyinggu.BusinessEntities
{
	/// <summary>
	/// SubjectCategory业务实体
	/// </summary>
#if EnableWCF
	[DataContract] [Serializable]
#else
	[Serializable]
#endif
	public partial class SubjectCategory : SubjectCategoryBase
	{
		#region Constructor
		/// <summary>
		/// SubjectCategory构造函数--默认
		/// </summary>
		public SubjectCategory()
			: base()
		{
		}
		
		/// <summary>
		/// SubjectCategory构造函数--所有属性
		/// </summary>
		/// <param name="id">Id</param>
		/// <param name="subjectCategoryName">SubjectCategoryName</param>
		public SubjectCategory(Int32 id, String subjectCategoryName)
			: base(id, subjectCategoryName)
		{
		}
		
		#endregion Constructor
	}
	
	/// <summary>
	/// SubjectCategory业务实体基类
	/// </summary>
#if EnableWCF
	[DataContract] [Serializable]
#else
	[Serializable]
#endif
	public abstract partial class SubjectCategoryBase
	{
		#region Constructor
		/// <summary>
		/// SubjectCategory构造函数--默认
		/// </summary>
		protected SubjectCategoryBase()
		{
		}
		
		/// <summary>
		/// SubjectCategory构造函数--所有属性
		/// </summary>
		/// <param name="id">Id</param>
		/// <param name="subjectCategoryName">SubjectCategoryName</param>
		protected SubjectCategoryBase(Int32 id, String subjectCategoryName)
		{
			this.idField = id;
			this.subjectCategoryNameField = subjectCategoryName;
		}
		
		#endregion Constructor
		
		#region Fields, Properties
		private Int32 idField;
		/// <summary>
		/// Id
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual Int32 Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
		
		private String subjectCategoryNameField;
		/// <summary>
		/// SubjectCategoryName
		/// </summary>
#if EnableWCF
		[DataMember]
#endif
		public virtual String SubjectCategoryName
		{
			get
			{
				return this.subjectCategoryNameField;
			}
			set
			{
				this.subjectCategoryNameField = value;
			}
		}
		
		#endregion Fields, Properties
	}
}
