/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Users业务实体列表
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/19 16:01:26
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Text;

using System.Collections;
#if EnableWCF
using System.Runtime.Serialization;
#endif

namespace Zkjj.Zgyinggu.BusinessEntities
{
	/// <summary>
	/// Users业务实体列表
	/// </summary>
#if EnableWCF
	[CollectionDataContract] [Serializable]
#else
	[Serializable]
#endif
	public sealed class UsersList : List<Users>
	{
		/// <summary>
		/// 查找所有满足条件的Users
		/// </summary>
		/// <param name="match">Users查找条件</param>
		/// <returns>Users业务实体列表</returns>
		public new UsersList FindAll(Predicate<Users> match)
		{
			if (match == null)
			{
				throw new ArgumentNullException("match");
			}
			
			UsersList list = new UsersList();
			
			for (int i = 0; i < this.Count; i++)
			{
				if (match(this[i]))
				{
					list.Add(this[i]);
				}
			}
			
			return list;
		}
	}
}
