/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Comment数据访问
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Globalization;
using System.Text;

using Microsoft.ApplicationBlocks.Data;

using Share.Framework.Data;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#endif

namespace Zkjj.Zgyinggu.DataAccess.SQLServer
{
	/// <summary>
	/// Comment数据访问
	/// </summary>
	public partial class CommentDataAccess : CommentDataAccessBase
#if EnableIDAL
		, ICommentDataAccess
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// Comment数据访问基类
	/// </summary>
	public class CommentDataAccessBase
	{

		/// <summary>
		/// 增加（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="comment">Comment</param>
		public virtual void Add(DbTransaction transaction, Comment comment)
		{
			string commandName = "Pr_Comment_I";
						
			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int),
					new SqlParameter("@CommentContent", SqlDbType.NVarChar, 500),
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@CreatorId", SqlDbType.Int),
					new SqlParameter("@CreatorName", SqlDbType.NChar, 10),
					new SqlParameter("@CreateTime", SqlDbType.DateTime)
					};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}

			#region 输出参数设置
			parms[0].Direction = ParameterDirection.InputOutput;
			#endregion
			
			#region 参数赋值
			parms[1].Value = comment.CommentContent;
			parms[2].Value = comment.SubjectId;
			parms[3].Value = comment.CreatorId;
			parms[4].Value = comment.CreatorName;
			parms[5].Value = comment.CreateTime;
			#endregion
			#endregion			
		
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Insert, null);
				throw;
			}

			#region 获取输出参数值
			comment.Id = (Int32)parms[0].Value;
			#endregion
		}

		///// <summary>
		///// 增加
		///// </summary>
		///// <param name="comment">Comment</param>
		//public virtual void Add(Comment comment)
		//{
		//  Add(null, comment);
		//}
		
		/// <summary>
		/// 删除（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="id">Id</param>
		public virtual void Remove(DbTransaction transaction, Int32 id)
		{
			string commandName = "Pr_Comment_D";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = id;
			#endregion
			#endregion
						
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Delete, new string[] { id.ToString() });
				throw;
			}
		}

		///// <summary>
		///// 删除
		///// </summary>
		///// <param name="id">Id</param>
		//public virtual void Remove(Int32 id)
		//{
		//  Remove(null, id);
		//}
		
		/// <summary>
		/// 保存（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="comment">Comment</param>
		public virtual void Save(DbTransaction transaction, Comment comment)
		{
			string commandName = "Pr_Comment_U";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int),
					new SqlParameter("@CommentContent", SqlDbType.NVarChar, 500),
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@CreatorId", SqlDbType.Int),
					new SqlParameter("@CreatorName", SqlDbType.NChar, 10),
					new SqlParameter("@CreateTime", SqlDbType.DateTime)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = comment.Id;
			parms[1].Value = comment.CommentContent;
			parms[2].Value = comment.SubjectId;
			parms[3].Value = comment.CreatorId;
			parms[4].Value = comment.CreatorName;
			parms[5].Value = comment.CreateTime;
			#endregion
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Update, null);
				throw;
			}
		}

		///// <summary>
		///// 保存
		///// </summary>
		///// <param name="comment">Comment</param>
		//public virtual void Save(Comment comment)
		//{
		//  Save(null, comment);
		//}
		
		/// <summary>
		/// 获取新ID（序列）
		/// </summary>
		/// <returns>新ID</returns>
		public virtual decimal GetNewId()
		{
			string commandText = @"SELECT S_Comment.nextval FROM DUAL;";

			return (decimal)OracleHelper.ExecuteScalar(ConnectionString.ZgyinguWrite, CommandType.Text, commandText, null);
		}
		
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		/// <param name="id">Id</param>
		/// <returns>Comment</returns>
		public virtual Comment GetById(Int32 id)
		{
			Comment comment = null;
			
			string commandName = "Query_Comment_GetByPk";
			string commandText = @"
SELECT *
FROM Comment
WHERE
 Id = :p_Id";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = id;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				if (dataReader.Read())
				{
					comment = PopulateCommentFromDataReader(dataReader);
				}
			}
			
			return comment;
		}
	
		/// <summary>
		/// 获取所有对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Comment列表</returns>
		public virtual CommentList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression, out int totalRecords)
		{
			CommentList commentList = new CommentList();
			
			string commandName = "Query_Comment_GetPagedListAll";
			string commandText = string.Format(@"
SELECT * FROM 
(SELECT a.*, ROWNUM RIndex FROM 
(SELECT * FROM Comment t {0}) a
) b WHERE RIndex > :p_startRowIndex AND RIndex <= :p_endRowIndex",
				string.IsNullOrEmpty(sortExpression) ? "" : "ORDER BY " + sortExpression);

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("p_startRowIndex", SqlDbType.Int),
					new SqlParameter("p_endRowIndex", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			parms[0].Value = startRowIndex;
			parms[1].Value = startRowIndex + maximumRows;
			#endregion
			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				while (dataReader.Read())
				{
					commentList.Add(PopulateCommentFromDataReader(dataReader));
				}
			}
			
			commandText = @"
SELECT COUNT(*) FROM Comment";
			totalRecords = Convert.ToInt32(SqlHelper.ExecuteScalar(ConnectionString.ZgyinguRead, CommandType.Text, commandText, null));
			
			return commentList;
		}
		
		/// <summary>
		/// 根据条件获取对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Comment列表</returns>
		public virtual CommentList GetPagedListByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria, out int totalRecords)
		{
			CommentList commentList = new CommentList();
			
			string commandName = "Query_Comment_GetPagedListByCriteria";
			string commandText = string.Format(@"
SELECT * FROM 
(SELECT a.*, ROWNUM RIndex FROM 
(SELECT * FROM Comment t WHERE 1=1 {1} {0}) a
) b WHERE RIndex > :p_startRowIndex AND RIndex <= :p_endRowIndex",
				string.IsNullOrEmpty(sortExpression) ? "" : "ORDER BY " + sortExpression,
				criteria);

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("p_startRowIndex", SqlDbType.Int),
					new SqlParameter("p_endRowIndex", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			parms[0].Value = startRowIndex;
			parms[1].Value = startRowIndex + maximumRows;
			#endregion
			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				while (dataReader.Read())
				{
					commentList.Add(PopulateCommentFromDataReader(dataReader));
				}
			}
			
			commandText = string.Format(@"
SELECT COUNT(*) FROM Comment WHERE 1=1 {0} ",
				criteria);;
			totalRecords = Convert.ToInt32(SqlHelper.ExecuteScalar(ConnectionString.ZgyinguRead, CommandType.Text, commandText, null));
			
			return commentList;
		}
		
		/// <summary>
		/// 从DataReader中读取数据到业务对象
		/// </summary>
		/// <param name="reader">DataReader</param>
		/// <returns>Comment</returns>
		protected virtual Comment PopulateCommentFromDataReader(SqlDataReader reader)
		{
			return DataReaderUtility.FillData<Comment>(reader);
		}
	}
}
