/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	SubjectInfo数据访问
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Globalization;
using System.Text;

using Microsoft.ApplicationBlocks.Data;

using Share.Framework.Data;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#endif

namespace Zkjj.Zgyinggu.DataAccess.SQLServer
{
	/// <summary>
	/// SubjectInfo数据访问
	/// </summary>
	public partial class SubjectInfoDataAccess : SubjectInfoDataAccessBase
#if EnableIDAL
		, ISubjectInfoDataAccess
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// SubjectInfo数据访问基类
	/// </summary>
	public class SubjectInfoDataAccessBase
	{

		/// <summary>
		/// 增加（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="subjectInfo">SubjectInfo</param>
		public virtual void Add(DbTransaction transaction, SubjectInfo subjectInfo)
		{
			string commandName = "Pr_SubjectInfo_I";
						
			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int),
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@FileName", SqlDbType.NVarChar, 50),
					new SqlParameter("@FileUrl", SqlDbType.NVarChar, 200)
					};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}

			#region 输出参数设置
			parms[0].Direction = ParameterDirection.InputOutput;
			#endregion
			
			#region 参数赋值
			if (subjectInfo.SubjectId != null){ parms[1].Value = subjectInfo.SubjectId; } else { parms[1].Value = DBNull.Value; }
			if (subjectInfo.FileName != null){ parms[2].Value = subjectInfo.FileName; } else { parms[2].Value = DBNull.Value; }
			if (subjectInfo.FileUrl != null){ parms[3].Value = subjectInfo.FileUrl; } else { parms[3].Value = DBNull.Value; }
			#endregion
			#endregion			
		
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Insert, null);
				throw;
			}

			#region 获取输出参数值
			subjectInfo.Id = (Int32)parms[0].Value;
			#endregion
		}

		///// <summary>
		///// 增加
		///// </summary>
		///// <param name="subjectInfo">SubjectInfo</param>
		//public virtual void Add(SubjectInfo subjectInfo)
		//{
		//  Add(null, subjectInfo);
		//}
		
		/// <summary>
		/// 删除（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="id">Id</param>
		public virtual void Remove(DbTransaction transaction, Int32 id)
		{
			string commandName = "Pr_SubjectInfo_D";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = id;
			#endregion
			#endregion
						
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Delete, new string[] { id.ToString() });
				throw;
			}
		}

		///// <summary>
		///// 删除
		///// </summary>
		///// <param name="id">Id</param>
		//public virtual void Remove(Int32 id)
		//{
		//  Remove(null, id);
		//}
		
		/// <summary>
		/// 保存（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="subjectInfo">SubjectInfo</param>
		public virtual void Save(DbTransaction transaction, SubjectInfo subjectInfo)
		{
			string commandName = "Pr_SubjectInfo_U";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int),
					new SqlParameter("@SubjectId", SqlDbType.Int),
					new SqlParameter("@FileName", SqlDbType.NVarChar, 50),
					new SqlParameter("@FileUrl", SqlDbType.NVarChar, 200)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = subjectInfo.Id;
			if (subjectInfo.SubjectId != null){ parms[1].Value = subjectInfo.SubjectId; } else { parms[1].Value = DBNull.Value; }
			if (subjectInfo.FileName != null){ parms[2].Value = subjectInfo.FileName; } else { parms[2].Value = DBNull.Value; }
			if (subjectInfo.FileUrl != null){ parms[3].Value = subjectInfo.FileUrl; } else { parms[3].Value = DBNull.Value; }
			#endregion
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Update, null);
				throw;
			}
		}

		///// <summary>
		///// 保存
		///// </summary>
		///// <param name="subjectInfo">SubjectInfo</param>
		//public virtual void Save(SubjectInfo subjectInfo)
		//{
		//  Save(null, subjectInfo);
		//}
		
		/// <summary>
		/// 获取新ID（序列）
		/// </summary>
		/// <returns>新ID</returns>
		public virtual decimal GetNewId()
		{
			string commandText = @"SELECT S_SubjectInfo.nextval FROM DUAL;";

			return (decimal)OracleHelper.ExecuteScalar(ConnectionString.ZgyinguWrite, CommandType.Text, commandText, null);
		}
		
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		/// <param name="id">Id</param>
		/// <returns>SubjectInfo</returns>
		public virtual SubjectInfo GetById(Int32 id)
		{
			SubjectInfo subjectInfo = null;
			
			string commandName = "Query_SubjectInfo_GetByPk";
			string commandText = @"
SELECT *
FROM SubjectInfo
WHERE
 Id = :p_Id";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@Id", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = id;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				if (dataReader.Read())
				{
					subjectInfo = PopulateSubjectInfoFromDataReader(dataReader);
				}
			}
			
			return subjectInfo;
		}
	
		/// <summary>
		/// 获取所有对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>SubjectInfo列表</returns>
		public virtual SubjectInfoList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression, out int totalRecords)
		{
			SubjectInfoList subjectInfoList = new SubjectInfoList();
			
			string commandName = "Query_SubjectInfo_GetPagedListAll";
			string commandText = string.Format(@"
SELECT * FROM 
(SELECT a.*, ROWNUM RIndex FROM 
(SELECT * FROM SubjectInfo t {0}) a
) b WHERE RIndex > :p_startRowIndex AND RIndex <= :p_endRowIndex",
				string.IsNullOrEmpty(sortExpression) ? "" : "ORDER BY " + sortExpression);

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("p_startRowIndex", SqlDbType.Int),
					new SqlParameter("p_endRowIndex", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			parms[0].Value = startRowIndex;
			parms[1].Value = startRowIndex + maximumRows;
			#endregion
			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				while (dataReader.Read())
				{
					subjectInfoList.Add(PopulateSubjectInfoFromDataReader(dataReader));
				}
			}
			
			commandText = @"
SELECT COUNT(*) FROM SubjectInfo";
			totalRecords = Convert.ToInt32(SqlHelper.ExecuteScalar(ConnectionString.ZgyinguRead, CommandType.Text, commandText, null));
			
			return subjectInfoList;
		}
		
		/// <summary>
		/// 根据条件获取对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>SubjectInfo列表</returns>
		public virtual SubjectInfoList GetPagedListByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria, out int totalRecords)
		{
			SubjectInfoList subjectInfoList = new SubjectInfoList();
			
			string commandName = "Query_SubjectInfo_GetPagedListByCriteria";
			string commandText = string.Format(@"
SELECT * FROM 
(SELECT a.*, ROWNUM RIndex FROM 
(SELECT * FROM SubjectInfo t WHERE 1=1 {1} {0}) a
) b WHERE RIndex > :p_startRowIndex AND RIndex <= :p_endRowIndex",
				string.IsNullOrEmpty(sortExpression) ? "" : "ORDER BY " + sortExpression,
				criteria);

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("p_startRowIndex", SqlDbType.Int),
					new SqlParameter("p_endRowIndex", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			parms[0].Value = startRowIndex;
			parms[1].Value = startRowIndex + maximumRows;
			#endregion
			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				while (dataReader.Read())
				{
					subjectInfoList.Add(PopulateSubjectInfoFromDataReader(dataReader));
				}
			}
			
			commandText = string.Format(@"
SELECT COUNT(*) FROM SubjectInfo WHERE 1=1 {0} ",
				criteria);;
			totalRecords = Convert.ToInt32(SqlHelper.ExecuteScalar(ConnectionString.ZgyinguRead, CommandType.Text, commandText, null));
			
			return subjectInfoList;
		}
		
		/// <summary>
		/// 从DataReader中读取数据到业务对象
		/// </summary>
		/// <param name="reader">DataReader</param>
		/// <returns>SubjectInfo</returns>
		protected virtual SubjectInfo PopulateSubjectInfoFromDataReader(SqlDataReader reader)
		{
			return DataReaderUtility.FillData<SubjectInfo>(reader);
		}
	}
}
