/*
 * -------------------------------------------------------------------------------------------------
 * 版权信息：	中国英谷平台 版权所有 2015
 * 功能描述：	Users数据访问
 * 
 * 创建人：　	Chenjt
 * 创建日期：	2015/11/17 15:07:31
 * 创建说明：	自动生成代码，严禁修改
 * -------------------------------------------------------------------------------------------------
 * This file is generated by CodeGenerator(Ver 2.2), a product of ZhouYonghua(Zhou_Yonghua@163.com).
 * -------------------------------------------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Globalization;
using System.Text;

using Microsoft.ApplicationBlocks.Data;

using Share.Framework.Data;
using Share.Framework.Logging;

using Zkjj.Zgyinggu.BusinessEntities;
#if EnableIDAL
using Zkjj.Zgyinggu.DataAccess.Interface;
#endif

namespace Zkjj.Zgyinggu.DataAccess.SQLServer
{
	/// <summary>
	/// Users数据访问
	/// </summary>
	public partial class UsersDataAccess : UsersDataAccessBase
#if EnableIDAL
		, IUsersDataAccess
#endif
	{
		//Do Not Code Here!
	}
	
	/// <summary>
	/// Users数据访问基类
	/// </summary>
	public class UsersDataAccessBase
	{

		/// <summary>
		/// 增加（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="users">Users</param>
		public virtual void Add(DbTransaction transaction, Users users)
		{
			string commandName = "Pr_Users_I";
						
			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int),
					new SqlParameter("@UserName", SqlDbType.NVarChar, 50),
					new SqlParameter("@Password", SqlDbType.NVarChar, 100),
					new SqlParameter("@DisplayName", SqlDbType.NVarChar, 50),
					new SqlParameter("@UserHeadImg", SqlDbType.NVarChar, 200)
					};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}

			#region 输出参数设置
			parms[0].Direction = ParameterDirection.InputOutput;
			#endregion
			
			#region 参数赋值
			parms[1].Value = users.UserName;
			parms[2].Value = users.Password;
			parms[3].Value = users.DisplayName;
			parms[4].Value = users.UserHeadImg;
			#endregion
			#endregion			
		
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Insert, null);
				throw;
			}

			#region 获取输出参数值
			users.UserId = (Int32)parms[0].Value;
			#endregion
		}

		///// <summary>
		///// 增加
		///// </summary>
		///// <param name="users">Users</param>
		//public virtual void Add(Users users)
		//{
		//  Add(null, users);
		//}
		
		/// <summary>
		/// 删除（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="userId">UserId</param>
		public virtual void Remove(DbTransaction transaction, Int32 userId)
		{
			string commandName = "Pr_Users_D";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = userId;
			#endregion
			#endregion
						
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Delete, new string[] { userId.ToString() });
				throw;
			}
		}

		///// <summary>
		///// 删除
		///// </summary>
		///// <param name="userId">UserId</param>
		//public virtual void Remove(Int32 userId)
		//{
		//  Remove(null, userId);
		//}
		
		/// <summary>
		/// 保存（事务处理）
		/// </summary>
		/// <param name="transaction">事务</param>
		/// <param name="users">Users</param>
		public virtual void Save(DbTransaction transaction, Users users)
		{
			string commandName = "Pr_Users_U";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguWrite, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int),
					new SqlParameter("@UserName", SqlDbType.NVarChar, 50),
					new SqlParameter("@Password", SqlDbType.NVarChar, 100),
					new SqlParameter("@DisplayName", SqlDbType.NVarChar, 50),
					new SqlParameter("@UserHeadImg", SqlDbType.NVarChar, 200)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguWrite, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = users.UserId;
			parms[1].Value = users.UserName;
			parms[2].Value = users.Password;
			parms[3].Value = users.DisplayName;
			parms[4].Value = users.UserHeadImg;
			#endregion
			#endregion
			
			try
			{
				if (transaction == null)
				{
					SqlHelper.ExecuteNonQuery(ConnectionString.ZgyinguWrite, CommandType.StoredProcedure, commandName, parms);
				}
				else
				{
					SqlHelper.ExecuteNonQuery((SqlTransaction)transaction, CommandType.StoredProcedure, commandName, parms);
				}
			}
			catch (SqlException ex)
			{
				DBContraintExceptionHandler.Handle(ex, DBOperateType.Update, null);
				throw;
			}
		}

		///// <summary>
		///// 保存
		///// </summary>
		///// <param name="users">Users</param>
		//public virtual void Save(Users users)
		//{
		//  Save(null, users);
		//}
		
		/// <summary>
		/// 获取新ID（序列）
		/// </summary>
		/// <returns>新ID</returns>
		public virtual decimal GetNewId()
		{
			string commandText = @"SELECT S_Users.nextval FROM DUAL;";

			return (decimal)OracleHelper.ExecuteScalar(ConnectionString.ZgyinguWrite, CommandType.Text, commandText, null);
		}
		
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		/// <param name="userId">UserId</param>
		/// <returns>Users</returns>
		public virtual Users GetById(Int32 userId)
		{
			Users users = null;
			
			string commandName = "Query_Users_GetByPk";
			string commandText = @"
SELECT *
FROM Users
WHERE
 UserId = :p_UserId";

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("@UserId", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			#region 参数赋值
			parms[0].Value = userId;
			#endregion
			#endregion

			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				if (dataReader.Read())
				{
					users = PopulateUsersFromDataReader(dataReader);
				}
			}
			
			return users;
		}
	
		/// <summary>
		/// 获取所有对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Users列表</returns>
		public virtual UsersList GetPagedListAll(int startRowIndex, int maximumRows, string sortExpression, out int totalRecords)
		{
			UsersList usersList = new UsersList();
			
			string commandName = "Query_Users_GetPagedListAll";
			string commandText = string.Format(@"
SELECT * FROM 
(SELECT a.*, ROWNUM RIndex FROM 
(SELECT * FROM Users t {0}) a
) b WHERE RIndex > :p_startRowIndex AND RIndex <= :p_endRowIndex",
				string.IsNullOrEmpty(sortExpression) ? "" : "ORDER BY " + sortExpression);

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("p_startRowIndex", SqlDbType.Int),
					new SqlParameter("p_endRowIndex", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			parms[0].Value = startRowIndex;
			parms[1].Value = startRowIndex + maximumRows;
			#endregion
			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				while (dataReader.Read())
				{
					usersList.Add(PopulateUsersFromDataReader(dataReader));
				}
			}
			
			commandText = @"
SELECT COUNT(*) FROM Users";
			totalRecords = Convert.ToInt32(SqlHelper.ExecuteScalar(ConnectionString.ZgyinguRead, CommandType.Text, commandText, null));
			
			return usersList;
		}
		
		/// <summary>
		/// 根据条件获取对象列表（分页，可排序）
		/// </summary>
		/// <param name="startRowIndex">起始记录号</param>
		/// <param name="maximumRows">行数</param>
		/// <param name="sortExpression">排序表达式</param>
		/// <param name="criteria">查询条件(以And开头)</param>
		/// <param name="totalRecords">（返回）记录总数</param>
		/// <returns>Users列表</returns>
		public virtual UsersList GetPagedListByCriteria(int startRowIndex, int maximumRows, string sortExpression, string criteria, out int totalRecords)
		{
			UsersList usersList = new UsersList();
			
			string commandName = "Query_Users_GetPagedListByCriteria";
			string commandText = string.Format(@"
SELECT * FROM 
(SELECT a.*, ROWNUM RIndex FROM 
(SELECT * FROM Users t WHERE 1=1 {1} {0}) a
) b WHERE RIndex > :p_startRowIndex AND RIndex <= :p_endRowIndex",
				string.IsNullOrEmpty(sortExpression) ? "" : "ORDER BY " + sortExpression,
				criteria);

			#region Parameters
			SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ZgyinguRead, commandName);
			if (parms == null)
			{
				parms = new SqlParameter[] {
					new SqlParameter("p_startRowIndex", SqlDbType.Int),
					new SqlParameter("p_endRowIndex", SqlDbType.Int)
				};
				SqlHelperParameterCache.CacheParameterSet(ConnectionString.ZgyinguRead, commandName, parms);
			}
			
			parms[0].Value = startRowIndex;
			parms[1].Value = startRowIndex + maximumRows;
			#endregion
			using (SqlDataReader dataReader = SqlHelper.ExecuteReader(ConnectionString.ZgyinguRead, CommandType.Text, commandText, parms))
			{
				while (dataReader.Read())
				{
					usersList.Add(PopulateUsersFromDataReader(dataReader));
				}
			}
			
			commandText = string.Format(@"
SELECT COUNT(*) FROM Users WHERE 1=1 {0} ",
				criteria);;
			totalRecords = Convert.ToInt32(SqlHelper.ExecuteScalar(ConnectionString.ZgyinguRead, CommandType.Text, commandText, null));
			
			return usersList;
		}
		
		/// <summary>
		/// 从DataReader中读取数据到业务对象
		/// </summary>
		/// <param name="reader">DataReader</param>
		/// <returns>Users</returns>
		protected virtual Users PopulateUsersFromDataReader(SqlDataReader reader)
		{
			return DataReaderUtility.FillData<Users>(reader);
		}
	}
}
